server.port=8088
spring.application.name=soporte

spring.datasource.url=${SOPORTE_DB_URL}
spring.datasource.username=${SOPORTE_DB_USERNAME}
spring.datasource.password=${SOPORTE_DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.security.oauth2.resourceserver.jwt.issuer-uri=${AZURE_ISSUER_URI:https://login.microsoftonline.com/3fb87110-4624-4d64-8806-a2304cfbbceb/v2.0}
spring.security.oauth2.resourceserver.jwt.audiences=${AZURE_API_AUDIENCE:4974cb3b-f538-4df9-8aec-d2c5dca687d0}
