server.port=8087
spring.application.name=solicitudes

spring.datasource.url=jdbc:mysql://fifas-db.c0dwcxryyla0.us-east-1.rds.amazonaws.com:3306/erp_cloud?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=admin
spring.datasource.password=${SOLICITUDES_DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.security.oauth2.resourceserver.jwt.issuer-uri=${AZURE_ISSUER_URI:https://login.microsoftonline.com/3fb87110-4624-4d64-8806-a2304cfbbceb/v2.0}
spring.security.oauth2.resourceserver.jwt.audiences=${AZURE_API_AUDIENCE:4974cb3b-f538-4df9-8aec-d2c5dca687d0}
