server.port=8089
spring.application.name=bff
spring.security.oauth2.resourceserver.jwt.issuer-uri=${AZURE_ISSUER_URI:https://login.microsoftonline.com/3fb87110-4624-4d64-8806-a2304cfbbceb/v2.0}
spring.security.oauth2.resourceserver.jwt.audiences=${AZURE_API_AUDIENCE:4974cb3b-f538-4df9-8aec-d2c5dca687d0}

logging.level.org.springframework.security=${SECURITY_LOG_LEVEL:INFO}
